set(CMAKE_BUILD_TYPE MinSizeRel CACHE STRING "")

# Stage 1 Bootstrap Setup
set(CLANG_ENABLE_BOOTSTRAP ON CACHE BOOL "")
set(CLANG_BOOTSTRAP_TARGETS
	generate-profdata
	stage3
	stage3-clang
	stage3-distribution
	stage3-install
	stage3-install-stripped
	stage3-install-distribution
	stage3-install-distribution-toolchain
	stage3-check-all
	stage3-check-llvm
	stage3-check-clang
	stage3-test-suite
	CACHE STRING ""
)

# Stage 1 Options
set(LLVM_ENABLE_PROJECTS "clang;lld" CACHE STRING "")
set(LLVM_ENABLE_RUNTIMES "compiler-rt" CACHE STRING "")
set(LLVM_TARGETS_TO_BUILD Native CACHE STRING "")

# Stage 2 Bootstrap Setup
set(BOOTSTRAP_CLANG_ENABLE_BOOTSTRAP ON CACHE STRING "")
set(BOOTSTRAP_CLANG_BOOTSTRAP_TARGETS
	clang
  check-all
  check-llvm
  check-clang
	CACHE STRING ""
)

# Stage 2 Options
set(BOOTSTRAP_LLVM_BUILD_INSTRUMENTED IR CACHE STRING "")
set(BOOTSTRAP_LLVM_ENABLE_PROJECTS "clang;lld" CACHE STRING "")
set(BOOTSTRAP_LLVM_ENABLE_RUNTIMES "compiler-rt" CACHE STRING "")
set(BOOTSTRAP_LLVM_TARGETS_TO_BUILD Native CACHE STRING "")
set(BOOTSTRAP_LLVM_ENABLE_LTO Thin CACHE STRING "")
set(BOOTSTRAP_LLVM_ENABLE_LLD ON CACHE BOOL "")

# Stage 3 Options
set(BOOTSTRAP_BOOTSTRAP_LLVM_ENABLE_LLD ON CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_LLVM_ENABLE_PROJECTS "clang;lld;lldb;clang-tools-extra;bolt;polly;mlir;flang;libclc" CACHE STRING "")
set(BOOTSTRAP_BOOTSTRAP_LLVM_ENABLE_RUNTIMES "compiler-rt;libcxx;libcxxabi;libunwind" CACHE STRING "")
set(BOOTSTRAP_BOOTSTRAP_LLVM_RUNTIME_TARGETS "x86_64-unknown-linux-gnu" CACHE STRING "")
set(BOOTSTRAP_BOOTSTRAP_LLVM_EXPERIMENTAL_TARGETS_TO_BUILD "DirectX" CACHE STRING "")
set(BOOTSTRAP_BOOTSTRAP_CLANG_DEFAULT_UNWINDLIB libunwind CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_CLANG_DEFAULT_CXX_STDLIB libc++ CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_CLANG_DEFAULT_LINKER lld CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_CLANG_DEFAULT_OBJCOPY llvm-objcopy CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_CLANG_DEFAULT_RTLIB compiler-rt CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_CLANG_PLUGIN_SUPPORT OFF CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_LLVM_ENABLE_EH ON CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_LLVM_ENABLE_RTTI ON CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_LLVM_ENABLE_PIC ON CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_LLVM_ENABLE_LIBXML2 OFF CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_LIBCXX_INSTALL_MODULES ON CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_LIBCXX_ENABLE_STATIC_ABI_LIBRARY ON CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_LIBCXX_USE_COMPILER_RT ON CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_LIBCXX_USE_COMPILER_RT ON CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_LIBCXX_ENABLE_SHARED OFF CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_LIBCXX_HAS_GCC_LIB OFF CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_LIBCXX_HAS_GCC_LIB OFF CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_LIBCXX_HAS_GCC_S_LIB OFF CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_LIBCXX_HAS_ATOMIC_LIB OFF CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_LLIBCXX_STATICALLY_LINK_ABI_IN_STATIC_LIBRARY ON CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_LIBUNWIND_USE_COMPILER_RT ON CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_LIBUNWIND_INSTALL_HEADERS ON CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_LIBCXXABI_USE_COMPILER_RT ON CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_LIBCXXABI_USE_LLVM_UNWINDER ON CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_LIBCXXABI_ENABLE_STATIC_UNWINDER ON CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_COMPILER_RT_USE_BUILTINS_LIBRARY ON CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_COMPILER_RT_HAS_GCC_S_LIB OFF CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_LLVM_TOOL_REMARKS_SHLIB_BUILD OFF CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_LLVM_LINK_LLVM_DYLIB OFF CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_LLVM_BUILD_LLVM_DYLIB OFF CACHE BOOL "")
set(BOOTSTRAP_BOOTSTRAP_CLANG_ENABLE_HLSL ON CACHE BOOL "")
