#!/bin/sh
set -eu

cmake -B build -G Ninja \
	-S llvm-project/llvm \
	-DBUILD_SHARED_LIBS=OFF \
	-DCMAKE_INSTALL_PREFIX=$PWD/install \
	-DCMAKE_BUILD_TYPE=MinSizeRel \
	-C $PWD/theos.cmake \
	-DLLVM_CCACHE_BUILD=OFF \
	-DLLVM_INCLUDE_TESTS=OFF \
	-DLLVM_INCLUDE_EXAMPLES=OFF \
	-DLLVM_INCLUDE_BENCHMARKS=OFF \
	-DLLVM_DEFAULT_TARGET_TRIPLE=x86_64-unknown-linux-gnu \
	-DCLANG_DEFAULT_UNWINDLIB=libunwind \
	-DCLANG_DEFAULT_CXX_STDLIB=libc++ \
	-DCLANG_DEFAULT_LINKER=lld \
	-DCLANG_DEFAULT_OBJCOPY=llvm-objcopy \
	-DCLANG_DEFAULT_RTLIB=compiler-rt \
	-DCLANG_PLUGIN_SUPPORT=OFF \
	-DLLVM_ENABLE_EH=ON \
	-DLLVM_ENABLE_RTTI=ON \
	-DLLVM_ENABLE_PIC=ON \
	-DLLVM_ENABLE_LIBXML2=OFF \
	-DLLVM_ENABLE_PROJECTS="mlir;bolt;polly;libclc;clang;lld;clang-tools-extra;lldb" \
	-DLLVM_ENABLE_RUNTIMES="compiler-rt;libcxx;libcxxabi;libunwind" \
	-DLLVM_RUNTIME_TARGETS="x86_64-unknown-linux-gnu" \
	-DRUNTIMES_x86_64-unknown-linux-gnu_LIBCXX_INSTALL_MODULES=ON \
	-DRUNTIMES_x86_64-unknown-linux-gnu_LIBCXX_ENABLE_STATIC_ABI_LIBRARY=ON \
	-DRUNTIMES_x86_64-unknown-linux-gnu_LIBCXX_USE_COMPILER_RT=ON \
	-DRUNTIMES_x86_64-unknown-linux-gnu_LIBCXX_USE_COMPILER_RT=ON \
	-DRUNTIMES_x86_64-unknown-linux-gnu_LIBCXX_ENABLE_SHARED=OFF \
	-DRUNTIMES_x86_64-unknown-linux-gnu_LIBCXX_HAS_GCC_LIB=OFF \
	-DRUNTIMES_x86_64-unknown-linux-gnu_LIBCXX_HAS_GCC_LIB=OFF \
	-DRUNTIMES_x86_64-unknown-linux-gnu_LIBCXX_HAS_GCC_S_LIB=OFF \
	-DRUNTIMES_x86_64-unknown-linux-gnu_LIBCXX_HAS_ATOMIC_LIB=OFF \
	-DRUNTIMES_x86_64-unknown-linux-gnu_LLIBCXX_STATICALLY_LINK_ABI_IN_STATIC_LIBRARY=ON \
	-DRUNTIMES_x86_64-unknown-linux-gnu_LIBUNWIND_USE_COMPILER_RT=ON \
	-DRUNTIMES_x86_64-unknown-linux-gnu_LIBUNWIND_INSTALL_HEADERS=ON \
	-DRUNTIMES_x86_64-unknown-linux-gnu_LIBCXXABI_USE_COMPILER_RT=ON \
	-DRUNTIMES_x86_64-unknown-linux-gnu_LIBCXXABI_USE_LLVM_UNWINDER=ON \
	-DRUNTIMES_x86_64-unknown-linux-gnu_LIBCXXABI_ENABLE_STATIC_UNWINDER=ON \
	-DRUNTIMES_x86_64-unknown-linux-gnu_COMPILER_RT_USE_BUILTINS_LIBRARY=ON \
	-DRUNTIMES_x86_64-unknown-linux-gnu_COMPILER_RT_HAS_GCC_S_LIB=OFF \
	-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD="DirectX" \
	-DLLVM_TOOL_REMARKS_SHLIB_BUILD=OFF \
	-DLLVM_LINK_LLVM_DYLIB=OFF \
	-DLLVM_BUILD_LLVM_DYLIB=OFF \
	-DCLANG_ENABLE_HLSL=ON
ninja -C build install/strip

